hash-format = "sha256"

[[files]]
file = "mods/0,5-hp.pw.toml"
metafile = true

[[files]]
file = "mods/advancement-plaques.pw.toml"
metafile = true

[[files]]
file = "mods/ai-improvements.pw.toml"
metafile = true

[[files]]
file = "mods/ambiance.pw.toml"
metafile = true

[[files]]
file = "mods/ambient-environment.pw.toml"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
metafile = true

[[files]]
file = "mods/annoying-stuff-remover.pw.toml"
metafile = true

[[files]]
file = "mods/apples-plus.pw.toml"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/attributefix.pw.toml"
metafile = true

[[files]]
file = "mods/auditory-continued.pw.toml"
metafile = true

[[files]]
file = "mods/auth-me.pw.toml"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
metafile = true

[[files]]
file = "mods/bellsandwhistles.pw.toml"
metafile = true

[[files]]
file = "mods/better-advancements.pw.toml"
metafile = true

[[files]]
file = "mods/better-clouds.pw.toml"
metafile = true

[[files]]
file = "mods/better-compatibility-checker.pw.toml"
metafile = true

[[files]]
file = "mods/better-mods-button.pw.toml"
metafile = true

[[files]]
file = "mods/better-ping-display.pw.toml"
metafile = true

[[files]]
file = "mods/better-safe-bed.pw.toml"
metafile = true

[[files]]
file = "mods/better-third-person.pw.toml"
metafile = true

[[files]]
file = "mods/betteraddserver.pw.toml"
metafile = true

[[files]]
file = "mods/boat-item-view.pw.toml"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
metafile = true

[[files]]
file = "mods/bundle-scroll.pw.toml"
metafile = true

[[files]]
file = "mods/c2me-neoforge.pw.toml"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
metafile = true

[[files]]
file = "mods/chatnotify.pw.toml"
metafile = true

[[files]]
file = "mods/clean-tooltips.pw.toml"
metafile = true

[[files]]
file = "mods/client-tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/clientsort.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/coastal-waves.pw.toml"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
metafile = true

[[files]]
file = "mods/colorful-hearts.pw.toml"
metafile = true

[[files]]
file = "mods/colorful-subtitles.pw.toml"
metafile = true

[[files]]
file = "mods/configuration.pw.toml"
metafile = true

[[files]]
file = "mods/connector.pw.toml"
metafile = true

[[files]]
file = "mods/cook-your-food.pw.toml"
metafile = true

[[files]]
file = "mods/coordinated-compass.pw.toml"
metafile = true

[[files]]
file = "mods/craftingxp.pw.toml"
metafile = true

[[files]]
file = "mods/create-copper-zinc.pw.toml"
metafile = true

[[files]]
file = "mods/create-deep-dark.pw.toml"
metafile = true

[[files]]
file = "mods/create-encased.pw.toml"
metafile = true

[[files]]
file = "mods/create-framed.pw.toml"
metafile = true

[[files]]
file = "mods/create-simple-ore-doubling.pw.toml"
metafile = true

[[files]]
file = "mods/create-trimmed.pw.toml"
metafile = true

[[files]]
file = "mods/create-ultimate-factory.pw.toml"
metafile = true

[[files]]
file = "mods/create.pw.toml"
metafile = true

[[files]]
file = "mods/create_oxidized.pw.toml"
metafile = true

[[files]]
file = "mods/cristel-lib.pw.toml"
metafile = true

[[files]]
file = "mods/custom-window-title.pw.toml"
metafile = true

[[files]]
file = "mods/death-coordinates.pw.toml"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
metafile = true

[[files]]
file = "mods/draggable-lists.pw.toml"
metafile = true

[[files]]
file = "mods/dripsounds.pw.toml"
metafile = true

[[files]]
file = "mods/dungeon-delight.pw.toml"
metafile = true

[[files]]
file = "mods/dyed-bundles.pw.toml"
metafile = true

[[files]]
file = "mods/easy-anvils.pw.toml"
metafile = true

[[files]]
file = "mods/emi-ores.pw.toml"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
metafile = true

[[files]]
file = "mods/end-villager-trader.pw.toml"
metafile = true

[[files]]
file = "mods/endrem.pw.toml"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
metafile = true

[[files]]
file = "mods/euphonium.pw.toml"
metafile = true

[[files]]
file = "mods/expanded-delight.pw.toml"
metafile = true

[[files]]
file = "mods/experimentalist.pw.toml"
metafile = true

[[files]]
file = "mods/explorations.pw.toml"
metafile = true

[[files]]
file = "mods/extra-dungeons.pw.toml"
metafile = true

[[files]]
file = "mods/extrasoundsforge.pw.toml"
metafile = true

[[files]]
file = "mods/fallingleavesforge.pw.toml"
metafile = true

[[files]]
file = "mods/farlands-reborn.pw.toml"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
metafile = true

[[files]]
file = "mods/fast-minecart.pw.toml"
metafile = true

[[files]]
file = "mods/faster-random.pw.toml"
metafile = true

[[files]]
file = "mods/fastquit-forge.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/fishermens-trap.pw.toml"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
metafile = true

[[files]]
file = "mods/glassbreaker.pw.toml"
metafile = true

[[files]]
file = "mods/heart-crystals.pw.toml"
metafile = true

[[files]]
file = "mods/iceberg.pw.toml"
metafile = true

[[files]]
file = "mods/immersivethunder.pw.toml"
metafile = true

[[files]]
file = "mods/infinite-storage-bundle.pw.toml"
metafile = true

[[files]]
file = "mods/jade-addons-forge.pw.toml"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
metafile = true

[[files]]
file = "mods/kawaii-dishes.pw.toml"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
metafile = true

[[files]]
file = "mods/krypton-foxified.pw.toml"
metafile = true

[[files]]
file = "mods/ksyxis.pw.toml"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
metafile = true

[[files]]
file = "mods/larger-ore-veins-classic.pw.toml"
metafile = true

[[files]]
file = "mods/legendary-tooltips.pw.toml"
metafile = true

[[files]]
file = "mods/libjf.pw.toml"
metafile = true

[[files]]
file = "mods/lighty.pw.toml"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
metafile = true

[[files]]
file = "mods/log-filter.pw.toml"
metafile = true

[[files]]
file = "mods/longer-chat-history.pw.toml"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
metafile = true

[[files]]
file = "mods/lukis-crazy-chambers.pw.toml"
metafile = true

[[files]]
file = "mods/mcmouser.pw.toml"
metafile = true

[[files]]
file = "mods/mica.pw.toml"
metafile = true

[[files]]
file = "mods/mixintrace-reforged.pw.toml"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/moyai.pw.toml"
metafile = true

[[files]]
file = "mods/musket-mod.pw.toml"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
metafile = true

[[files]]
file = "mods/no-resource-pack-warnings-forge.pw.toml"
metafile = true

[[files]]
file = "mods/no-telemetry.pw.toml"
metafile = true

[[files]]
file = "mods/no-villager-death-messages.pw.toml"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
metafile = true

[[files]]
file = "mods/northerncompass.pw.toml"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
metafile = true

[[files]]
file = "mods/ok-zoomer.pw.toml"
metafile = true

[[files]]
file = "mods/open-parties-and-claims.pw.toml"
metafile = true

[[files]]
file = "mods/overflowing-bars.pw.toml"
metafile = true

[[files]]
file = "mods/paxi.pw.toml"
metafile = true

[[files]]
file = "mods/piglin-proliferation.pw.toml"
metafile = true

[[files]]
file = "mods/ping-wheel.pw.toml"
metafile = true

[[files]]
file = "mods/pling.pw.toml"
metafile = true

[[files]]
file = "mods/plushables.pw.toml"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
metafile = true

[[files]]
file = "mods/pretty-rain.pw.toml"
metafile = true

[[files]]
file = "mods/prickle.pw.toml"
metafile = true

[[files]]
file = "mods/prism-lib.pw.toml"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
metafile = true

[[files]]
file = "mods/rabbit-pathfinding-fix.pw.toml"
metafile = true

[[files]]
file = "mods/raised.pw.toml"
metafile = true

[[files]]
file = "mods/random-mob-sizes.pw.toml"
metafile = true

[[files]]
file = "mods/rebind-narrator.pw.toml"
metafile = true

[[files]]
file = "mods/reciperemover.pw.toml"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
metafile = true

[[files]]
file = "mods/remove-terralith-intro-message.pw.toml"
metafile = true

[[files]]
file = "mods/rsls.pw.toml"
metafile = true

[[files]]
file = "mods/rustic-pancakes.pw.toml"
metafile = true

[[files]]
file = "mods/screenshot-to-clipboard.pw.toml"
metafile = true

[[files]]
file = "mods/seamless.pw.toml"
metafile = true

[[files]]
file = "mods/slyde.pw.toml"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
metafile = true

[[files]]
file = "mods/sparsestructures.pw.toml"
metafile = true

[[files]]
file = "mods/spelunkers-palette.pw.toml"
metafile = true

[[files]]
file = "mods/stony-cliffs-are-cool.pw.toml"
metafile = true

[[files]]
file = "mods/structory.pw.toml"
metafile = true

[[files]]
file = "mods/superflat-world-no-slimes.pw.toml"
metafile = true

[[files]]
file = "mods/supplementaries-squared.pw.toml"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
metafile = true

[[files]]
file = "mods/text-formatting-everywhere.pw.toml"
metafile = true

[[files]]
file = "mods/tide.pw.toml"
metafile = true

[[files]]
file = "mods/tiny-item-animations.pw.toml"
metafile = true

[[files]]
file = "mods/tnt-breaks-bedrock.pw.toml"
metafile = true

[[files]]
file = "mods/toastbegone.pw.toml"
metafile = true

[[files]]
file = "mods/toggle-subtitles.pw.toml"
metafile = true

[[files]]
file = "mods/too-fast.pw.toml"
metafile = true

[[files]]
file = "mods/too-many-paintings.pw.toml"
metafile = true

[[files]]
file = "mods/trade-cycling.pw.toml"
metafile = true

[[files]]
file = "mods/vanilla-fireflies.pw.toml"
metafile = true

[[files]]
file = "mods/visual-workbench.pw.toml"
metafile = true

[[files]]
file = "mods/voidfog.pw.toml"
metafile = true

[[files]]
file = "mods/windchime-unofficial-continued.pw.toml"
metafile = true

[[files]]
file = "mods/world-start-commands-and-global-gamerules.pw.toml"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
metafile = true

[[files]]
file = "mods/yeetus-experimentus.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-jungle-temples.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-witch-huts.pw.toml"
metafile = true
