name = "Create: Fresh Start"
author = "Sammy L. Koch"
version = "1.2.0"
description = "It is time for a fresh start! Create v6 released with revolutionary changes!"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a08e5fdeab825afd34fcbe5cccc4eda18b55787f7ef2e97768d4711ff47ae4ba"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.138"
