name = "Create: Fresh Start"
author = "Sammy L. Koch"
version = "1.1.1"
description = "It is time for a fresh start! Create v6 released with revolutionary changes!"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2f59e147ca7e833200290ad26381a1860d4cb4306a15836e2da902a9a5c7606"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.138"
