name = "Create: Fresh Start"
author = "Sammy L. Koch"
version = "1.0.0"
description = "It is time for a fresh start! Create v6 released with revolutionary changes!"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2621e8c6af6c34ed9e1ee082cca1482069a1be3f8cccad9bc9a32a1daba8c64d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.138"

[options]
meta-folder = []
no-internal-hashes = true
